version: 2.1

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test-helloworld

jobs:
  test-helloworld:
    docker:
      - image: alpine
    steps:
      - run:
          name: running hello neel
          command: echo "Neel"

