version: 2.1

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test-helloworld

# apine-img: &apine-img
#   docker:
#     - image: apine

custom-img: &custom-img
  docker:
    - image: jadavneel70/test:v1.0.0

jobs:
  test-helloworld:
    <<: *custom-img
    steps:
      - run:
          name: starting app
          command: npm start
      # - run:
      #     name: installing docker
      #     command: apk add docker-cli
      # - run:
      #     name: pull image
      #     command: docker pull jadavneel70/test:v1.0.0
      # - run:
      #     name: docker build
      #     command: docker build -t sample jadavneel70/test:v1.0.0
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run:
      #     name: docker run
      #     command: docker run -it --rm --entrypoint bash jadavneel70/test:v1.0.0
