version: 2.1

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test-helloworld

node-img: &node-img
  docker:
    - image: node

jobs:
  test-helloworld:
    <<: *node-img
    steps:
      - checkout
      - run:
          name: running the app
          command: npm start
